# Generated by Django 2.2.6 on 2019-10-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_auto_20191005_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
